export enum Roles {
    ROLE_ADMIN          = "ROLE_ADMIN",
    ROLE_VISITOR        = "ROLE_VISITOR",
    ROLE_VISIT_HOMEPAGE = "ROLE_VISIT_HOMEPAGE",
    ROLE_VISIT_ABOUT    = "ROLE_VISIT_ABOUT",
    ROLE_VISIT_SONGS    = "ROLE_VISIT_SONGS",
    ROLE_VISIT_MOVIES   = "ROLE_VISIT_MOVIES",
    ROLE_VISIT_PERSONS  = "ROLE_VISIT_PERSONS",

    ROLE_UPDATE_PERSONS = "ROLE_UPDATE_PERSONS",
    ROLE_UPDATE_SONGS   = "ROLE_UPDATE_SONGS",
    ROLE_UPDATE_MOVIES  = "ROLE_UPDATE_MOVIES",
}
