export enum Roles {
    ROLE_VISIT_ACCOUNTS = "ROLE_VISIT_ACCOUNTS",
    ROLE_VISIT_MIXES = "ROLE_VISIT_MIXES",
    ROLE_UPDATE_ACCOUNTS = "ROLE_UPDATE_ACCOUNTS",
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_VISITOR = "ROLE_VISITOR",
    ROLE_VISIT_HOMEPAGE = "ROLE_VISIT_HOMEPAGE",
    ROLE_VISIT_ABOUT = "ROLE_VISIT_ABOUT",
    ROLE_VISIT_SONGS = "ROLE_VISIT_SONGS",
    ROLE_READ_ALL_FILES = "ROLE_READ_ALL_FILES",
    ROLE_VISIT_FILES = "ROLE_VISIT_FILES",
    ROLE_VISIT_MOVIES = "ROLE_VISIT_MOVIES",
    ROLE_VISIT_PERSONS = "ROLE_VISIT_PERSONS",

    ROLE_UPLOAD_FILES = "ROLE_UPLOAD_FILES",

    ROLE_UPDATE_PERSONS = "ROLE_UPDATE_PERSONS",
    ROLE_UPDATE_SONGS = "ROLE_UPDATE_SONGS",
    ROLE_UPDATE_MOVIES = "ROLE_UPDATE_MOVIES",
}
